### ISSUE TITLE
resoruces

### ISSUE THREAD

**Issue by alvarolorentedev** [CodeInBrackets/From-A-Galaxy-Far-Away#1]
![screen shot 2017-02-16 at 15 07 28](https://cloud.githubusercontent.com/assets/3071208/23041216/bc0821c0-f459-11e6-8c5f-cb571c882b5c.png)

**Comment by kanekotic** [comment]
![logomakr_3opzev](https://cloud.githubusercontent.com/assets/3071208/23041307/1e9bb0a4-f45a-11e6-9470-f8c55656f604.png)
